# Generated by Django 4.2.7 on 2024-02-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_alter_documenttype_optima_id"),
        ("warehouses", "0002_alter_warehouse_optima_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="document_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="documents.documenttype"
            ),
        ),
    ]
