# Generated by Django 4.2.7 on 2024-02-18 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0003_warehouse_document_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="document_type",
        ),
    ]
