# Generated by Django 4.2.7 on 2024-03-26 18:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service", "0036_alter_note_date_alter_note_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=1024, null=True)),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("country_code", models.CharField(max_length=5)),
                ("street", models.CharField(blank=True, max_length=200, null=True)),
                ("street_number", models.CharField(blank=True, max_length=12, null=True)),
                ("home_number", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=40, null=True)),
                ("post", models.CharField(blank=True, max_length=120, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("parcel_id", models.CharField(blank=True, max_length=120, null=True)),
                ("parcel_number", models.CharField(blank=True, max_length=120, null=True)),
                ("confirmation_id", models.CharField(blank=True, max_length=120, null=True)),
                ("label", models.FileField(blank=True, null=True, upload_to="labels")),
                (
                    "track_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=12, null=True), size=None
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping",
                        to="shipping.shippingaddress",
                    ),
                ),
                (
                    "service_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shipping", to="service.serviceorder"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
