# Generated by Django 4.2.7 on 2024-03-27 20:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0003_remove_shippingaddress_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping",
            name="track_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=12, null=True), blank=True, null=True, size=None
            ),
        ),
    ]
