# Generated by Django 4.2.7 on 2024-03-28 16:47

from django.db import migrations, models
import django.db.models.deletion


def set_null_countries(apps, schema_editor):
    ShippingAddress = apps.get_model('shipping', 'ShippingAddress')
    ShippingAddress.objects.all().update(country=None)


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0009_log_status"),
        ("shipping", "0004_alter_shipping_track_ids"),
    ]

    operations = [
        migrations.RunPython(set_null_countries),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="country_code",
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="crm_config.country"
            ),
        ),
    ]
