# Generated by Django 4.2.7 on 2024-04-02 19:05

from django.db import migrations


def create_statuses(apps, schema_editor):
    Status = apps.get_model('shipping', 'Status')
    definitions = (('PREADVICE', 'Preadvice'), ('INTRANSIT', 'In transit'), ('INWAREHOUSE', 'In warehouse'),
                   ('INDELIVERY', 'In delivery'), ('DELIVERED', 'Delivered'))
    for definition in definitions:
        Status.objects.create(code=definition[0], name=definition[1])


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0006_shipping_delivered_status_shippingstatus"),
    ]

    operations = [
        migrations.RunPython(create_statuses)
    ]
