# Generated by Django 4.2.7 on 2024-04-03 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0007_auto_20240402_1905"),
    ]

    operations = []
