# Generated by Django 4.2.7 on 2024-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0008_auto_20240403_2015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingstatus",
            name="date",
            field=models.DateField(),
        ),
    ]
