# Generated by Django 4.2.7 on 2024-04-04 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0010_alter_shippingstatus_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingstatus",
            name="date",
            field=models.DateField(default=datetime.date(2024, 4, 4)),
            preserve_default=False,
        ),
    ]
