# Generated by Django 4.2.7 on 2024-05-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0012_shippingcompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipping",
            name="shipping_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping",
                to="shipping.shippingcompany",
            ),
        ),
    ]
