# Generated by Django 4.2.7 on 2024-06-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0014_shippingmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="methods", to="shipping.shippingcompany"
            ),
        ),
    ]
