# Generated by Django 4.2.7 on 2024-06-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0015_alter_shippingmethod_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipping",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping",
                to="shipping.shippingmethod",
            ),
        ),
    ]
