# Generated by Django 4.2.7 on 2024-08-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0017_shippingmethod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcompany',
            name='track_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
