# Generated by Django 4.2.7 on 2024-03-03 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=10)),
                (
                    "product_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.productgroup"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
