# Generated by Django 4.2.7 on 2024-05-09 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_shipping_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="shipping_company",
        ),
    ]
