# Generated by Django 4.2.7 on 2023-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="home_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="optima_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
