# Generated by Django 4.2.7 on 2023-12-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0002_alter_contractor_home_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="phone_number",
            field=models.CharField(max_length=30),
        ),
    ]
