# Generated by Django 4.2.7 on 2023-12-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0003_alter_contractor_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
    ]
