# Generated by Django 4.2.7 on 2024-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0004_alter_contractor_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
