# Generated by Django 4.2.7 on 2024-01-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0005_contractor_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="name1",
            field=models.CharField(default=" ", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractor",
            name="name2",
            field=models.CharField(default=" ", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractor",
            name="name3",
            field=models.CharField(default=" ", max_length=1024),
            preserve_default=False,
        ),
    ]
