# Generated by Django 4.2.7 on 2024-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0006_contractor_name1_contractor_name2_contractor_name3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="code",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="home_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="name2",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="name3",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
