# Generated by Django 4.2.7 on 2024-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0008_alter_contractor_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="regon",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
