# Generated by Django 4.2.7 on 2023-12-20 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contractors", "0001_initial"),
        ("documents", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True)),
                ("exported", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=255)),
                ("code_detailed", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1024)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True)),
                ("exported", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1024)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True)),
                ("exported", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True)),
                ("exported", models.BooleanField(default=False)),
                ("type", models.IntegerField()),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True)),
                ("exported", models.BooleanField(default=False)),
                ("number_scheme", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("status", models.BooleanField(default=False)),
                (
                    "state",
                    models.IntegerField(choices=[(0, "Accepted"), (1, "In realization"), (2, "Realized")], default=0),
                ),
                ("document_date", models.DateTimeField()),
                ("acceptance_date", models.DateTimeField()),
                ("realization_date", models.DateTimeField()),
                ("closing_date", models.DateTimeField()),
                ("net_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gross_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_order",
                        to="service.category",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contractors.contractor"),
                ),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.device")),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_order",
                        to="documents.documenttype",
                    ),
                ),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.stage")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "warehouse",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="warehouses.warehouse"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.devicetype"),
        ),
    ]
