# Generated by Django 4.2.7 on 2023-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_serviceorder_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="optima_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="optima_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="optima_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="optima_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="stage",
            name="optima_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
