# Generated by Django 4.2.7 on 2023-12-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_alter_category_optima_id_alter_device_optima_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="stage",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="service.stage"),
        ),
    ]
