# Generated by Django 4.2.7 on 2023-12-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0004_alter_contractor_postal_code"),
        ("warehouses", "0002_alter_warehouse_optima_id"),
        ("service", "0004_alter_serviceorder_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="contractors.contractor"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="device",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="service.device"),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="warehouse",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="warehouses.warehouse"),
        ),
    ]
