# Generated by Django 4.2.7 on 2023-12-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0005_alter_serviceorder_contractor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="acceptance_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="closing_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="document_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="realization_date",
            field=models.DateTimeField(null=True),
        ),
    ]
