# Generated by Django 4.2.7 on 2024-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_alter_serviceorder_acceptance_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="full_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
