# Generated by Django 4.2.7 on 2024-01-17 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service", "0007_serviceorder_full_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_city",
            field=models.CharField(default=" ", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_country",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_home_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_name",
            field=models.CharField(default=" ", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_name1",
            field=models.CharField(default=" ", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_name2",
            field=models.CharField(default=" ", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_name3",
            field=models.CharField(default=" ", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_post",
            field=models.CharField(default=" ", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_postal_code",
            field=models.CharField(default=" ", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_state",
            field=models.CharField(default=" ", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_street",
            field=models.CharField(default=" ", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_street_number",
            field=models.CharField(default=" ", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="contractor_type",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Accepted"), (1, "In realization"), (2, "Realized"), (3, "Canceled"), (99, "New")],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("number", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("description", models.TextField(max_length=1024)),
                (
                    "service_order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.serviceorder"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
