# Generated by Django 4.2.7 on 2024-01-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_alter_documenttype_optima_id"),
        ("service", "0009_ordertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="purchase_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="purchase_document_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="serial_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_city",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_country",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_name",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_name1",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_name2",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_name3",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_post",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_postal_code",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_state",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_street",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_street_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="document_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_order",
                to="documents.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="number_scheme",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Accepted"), (1, "In realization"), (2, "Realized"), (3, "Canceled"), (99, "New")],
                default=99,
            ),
        ),
    ]
