# Generated by Django 4.2.7 on 2024-01-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0011_alter_serviceorder_gross_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="order_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="service.ordertype"),
        ),
    ]
