# Generated by Django 4.2.7 on 2024-02-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0012_serviceorder_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="invoice_file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
