# Generated by Django 4.2.7 on 2024-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0013_serviceorder_invoice_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceorder",
            name="invoice_file",
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="purchase_document",
            field=models.FileField(blank=True, null=True, upload_to="purchase_documents/"),
        ),
    ]
