# Generated by Django 4.2.7 on 2024-02-22 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0015_device_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("type", models.IntegerField()),
                ("code", models.CharField(max_length=150)),
                ("format", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttributeDefinitionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("value", models.CharField(max_length=300)),
                ("number", models.IntegerField()),
                (
                    "attribute_definition",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.attributedefinition"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=150)),
                ("value", models.CharField(max_length=300)),
                (
                    "attribute_definition",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.attributedefinition"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
