# Generated by Django 4.2.7 on 2024-02-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0016_attributedefinition_attributedefinitionitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="service_order",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="service.serviceorder"),
        ),
    ]
