# Generated by Django 4.2.7 on 2024-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0017_attribute_service_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="value",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="attributedefinitionitem",
            name="value",
            field=models.CharField(max_length=1000),
        ),
    ]
