# Generated by Django 4.2.7 on 2024-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0018_alter_attribute_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributedefinition",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
