# Generated by Django 4.2.7 on 2024-02-27 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0019_attributedefinition_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageDuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("start", models.DateTimeField(auto_now_add=True)),
                ("end", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "service_order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.serviceorder"),
                ),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.stage")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
