# Generated by Django 4.2.7 on 2024-02-27 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0020_stageduration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="form_files/")),
                (
                    "service_order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="service.serviceorder"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
