# Generated by Django 4.2.7 on 2024-02-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0021_formfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfile",
            name="service_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="form_files", to="service.serviceorder"
            ),
        ),
    ]
