# Generated by Django 4.2.7 on 2024-03-03 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0004_remove_warehouse_document_type"),
        ("products", "0001_initial"),
        ("users", "0006_user_created"),
        ("service", "0022_alter_formfile_service_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("number", models.IntegerField()),
                ("to_invoicing", models.BooleanField(default=False)),
                ("price_net", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_gross", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_collected", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_released", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=10)),
                ("to_return", models.BooleanField(default=False)),
                ("document", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_parts",
                        to="products.product",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_parts",
                        to="service.serviceorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_parts",
                        to="users.optimauser",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_parts",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
