# Generated by Django 4.2.7 on 2024-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0023_servicepart"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepart",
            name="status_collected",
            field=models.BooleanField(default=False),
        ),
    ]
