# Generated by Django 4.2.7 on 2024-03-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0024_servicepart_status_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepart",
            name="status_collected",
            field=models.IntegerField(),
        ),
    ]
