# Generated by Django 4.2.7 on 2024-03-04 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_created"),
        ("products", "0002_remove_product_product_group"),
        ("service", "0025_alter_servicepart_status_collected"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("number", models.IntegerField()),
                ("is_finished", models.BooleanField(default=False)),
                ("to_invoicing", models.BooleanField(default=False)),
                ("date_of_service", models.DateTimeField(blank=True, null=True)),
                ("date_from", models.DateTimeField(blank=True, null=True)),
                ("date_to", models.DateTimeField(blank=True, null=True)),
                ("price_net", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_gross", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("value_net", models.DecimalField(decimal_places=2, max_digits=10)),
                ("value_gross", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_activities",
                        to="products.product",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_activities",
                        to="service.serviceorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_activities",
                        to="users.optimauser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
