# Generated by Django 4.2.7 on 2024-03-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0026_serviceactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceactivity",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="price_discount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="price_gross",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="price_net",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="quantity",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="unit",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="value_gross",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="value_net",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
