# Generated by Django 4.2.7 on 2024-03-11 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contractors", "0007_alter_contractor_code_alter_contractor_home_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouses", "0004_remove_warehouse_document_type"),
        ("service", "0028_stage_email_template_emailsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="acceptance_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="closing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="contractors.contractor"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_city",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_home_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_name1",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_name2",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_name3",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_post",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_postal_code",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_state",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_street",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_street_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="device",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="service.device"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="document_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="full_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="gross_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="net_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="number_scheme",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="order_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="service.ordertype"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="purchase_document_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="realization_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="stage",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="service.stage"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="status",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="warehouse",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="warehouses.warehouse"
            ),
        ),
    ]
