# Generated by Django 4.2.7 on 2024-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0029_alter_serviceorder_acceptance_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
