# Generated by Django 4.2.7 on 2024-03-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0008_taxpercentage"),
        ("service", "0031_serviceactivity_service_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="email_template",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="crm_config.emailtemplate"
            ),
        ),
        migrations.AlterField(
            model_name="stageduration",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stageduration",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
