# Generated by Django 4.2.7 on 2024-03-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0032_alter_stage_email_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
