# Generated by Django 4.2.7 on 2024-03-13 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0033_alter_serviceorder_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceorder",
            old_name="status",
            new_name="in_buffer",
        ),
    ]
