# Generated by Django 4.2.7 on 2024-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0034_rename_status_serviceorder_in_buffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsent",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
