# Generated by Django 4.2.7 on 2024-04-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0036_alter_note_date_alter_note_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="service_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="service.serviceorder",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="contractor_country",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
