# Generated by Django 4.2.7 on 2024-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0037_alter_attribute_service_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceactivity",
            name="price_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
