# Generated by Django 4.2.7 on 2024-04-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0038_alter_serviceactivity_price_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceactivity",
            name="price_gross",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="value_gross",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="serviceactivity",
            name="value_net",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
