# Generated by Django 4.2.7 on 2024-04-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0039_alter_serviceactivity_price_gross_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceactivity",
            name="quantity",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
