# Generated by Django 4.2.7 on 2024-05-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0004_remove_warehouse_document_type"),
        ("service", "0040_alter_serviceactivity_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordertype",
            name="warehouse",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="warehouses.warehouse"
            ),
        ),
    ]
