# Generated by Django 4.2.7 on 2024-05-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0011_serviceaddress"),
        ("service", "0045_alter_stage_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="service_address",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="crm_config.serviceaddress"
            ),
        ),
    ]
