# Generated by Django 4.2.7 on 2024-06-05 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0046_serviceorder_service_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="device",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="device",
            name="device_catalog",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="service.devicecatalog"
            ),
        ),
    ]
