# Generated by Django 4.2.7 on 2024-06-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0047_devicecatalog_device_active_device_device_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicecatalog",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
