# Generated by Django 4.2.7 on 2024-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0048_devicecatalog_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="attribute",
        ),
        migrations.AddField(
            model_name="stage",
            name="attribute",
            field=models.ManyToManyField(to="service.attributedefinition"),
        ),
    ]
