# Generated by Django 4.2.7 on 2024-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0014_shippingmethod"),
        ("service", "0050_rename_attribute_stage_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="shipping_method",
            field=models.ManyToManyField(to="shipping.shippingmethod"),
        ),
    ]
