# Generated by Django 4.2.7 on 2024-06-30 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0051_device_shipping_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="shipping_company",
        ),
    ]
