# Generated by Django 4.2.7 on 2024-08-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_config', '0013_import'),
        ('service', '0053_device_available_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='available_services',
            field=models.ManyToManyField(blank=True, related_name='devices', to='crm_config.serviceaddress'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='service.devicecatalog'),
        ),
    ]
