# Generated by Django 4.2.7 on 2024-02-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0004_remove_warehouse_document_type"),
        ("documents", "0002_alter_documenttype_optima_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="warehouse",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="warehouses.warehouse"
            ),
        ),
    ]
