# Generated by Django 4.2.7 on 2024-08-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documenttype_to_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
