# Generated by Django 4.2.7 on 2024-03-07 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("template", models.TextField()),
                ("subject", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
