# Generated by Django 4.2.7 on 2024-03-09 10:10

from django.db import migrations, models

def create_general_settings(apps, schema_editor):
    GeneralSettings = apps.get_model('crm_config', 'GeneralSettings')
    if not GeneralSettings.objects.exists():
        GeneralSettings.objects.create()


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0004_generalsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="optima_general_database",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="optima_config_database",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(create_general_settings)
    ]
