# Generated by Django 4.2.7 on 2024-03-10 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0005_generalsettings_optima_general_database_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("exception_traceback", models.TextField(blank=True, null=True)),
                ("method_name", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255, null=True)),
                ("object_uuid", models.UUIDField(null=True)),
                ("object_serialized", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
