# Generated by Django 4.2.7 on 2024-03-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0006_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="number",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
