# Generated by Django 4.2.7 on 2024-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0009_log_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="admin_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
