# Generated by Django 4.2.7 on 2024-05-10 17:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0010_generalsettings_admin_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=1024, null=True)),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("street", models.CharField(blank=True, max_length=200, null=True)),
                ("street_number", models.CharField(blank=True, max_length=12, null=True)),
                ("home_number", models.IntegerField(blank=True, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=120, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="crm_config.country"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
