# Generated by Django 4.2.7 on 2024-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_config", "0011_serviceaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceaddress",
            name="opening_hours",
            field=models.TextField(blank=True, null=True),
        ),
    ]
