# Generated by Django 4.2.7 on 2024-01-17 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_name_user_first_name_user_last_name_user_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptimaUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("optima_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("exported", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=1024, verbose_name="Name")),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="optima_id",
        ),
        migrations.AddField(
            model_name="user",
            name="optima_user",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="user", to="users.optimauser"
            ),
        ),
    ]
